### ISSUE TITLE
[SPIKE] Investigate Code Solution for Parallel Browser and Mobile Banners in Knack Apps

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#20182]
**Background**:
* Knack apps using the standard banner is not adaptive to mobile screens well as currently implemented. 
* New optimized-for-mobile version have been created here: https://github.com/cityofaustin/atd-data-tech/issues/19558

**Spike**:
- Explore code to enable responsiveness to display the correct banner for the platform through which the application is being accessed
- See https://github.com/cityofaustin/atd-data-tech/issues/19558 for some initial notes on code options

**Comment by ChrispinP** [comment]
Did some testing with the CSS styling for headers and for apps where a banner image exists we can manipulate the image to be responsive for all screen sizes. We prevent the image from growing larger than 1000px for large screens. Below is the CSS Code tested as working.

```CSS
/*********************************************/
/******** Header Banner Image Styling ********/
/*********************************************/

/* Base styles for the image */
img.knHeader__logo-image {
  width: 100% !important;
  height: auto !important;
  max-width: 100% !important;
  object-fit: contain !important;
}

/* Base styles for the parent container */
.knHeader__logo.knHeader__logo--custom {
  height: auto !important;
  max-width: 1200px !important;
  margin: 0 0 0 0 !important; /* Left-justified */
}

/* Overrides for conflicting styles */
.knHeader .knHeader__logo--custom {
  width: 100% !important;
  max-width: 1200px !important;
  margin: 0 0 0 0 !important; /* Left-justified */
}

.knHeader .knHeader__logo .knHeader__logo-image {
  width: 100% !important;
  object-fit: contain !important;
}

/* Media queries for larger screens */
@media (min-width: 768px) {
  .knHeader__logo.knHeader__logo--custom {
    width: 80% !important;
  }
}

@media (min-width: 1024px) {
  .knHeader__logo.knHeader__logo--custom {
    width: 80% !important; /* Changed from 50% to 80% */
    max-width: 1200px !important;
  }
}

/* Media queries for image resizing */
@media (max-width: 767px) {
  .knHeader__logo.knHeader__logo--custom {
    width: 100% !important; /* Full width on small screens */
    max-width: 600px !important;
  }
}

@media (min-width: 768px) and (max-width: 1023px) {
  .knHeader__logo.knHeader__logo--custom {
    width: 80% !important; /* Medium width on medium screens */
    max-width: 800px !important;
  }
}
```
